---
- name: Check if GH GPG key is already present
  ansible.builtin.command:
    cmd: gpg --list-keys --keyring /etc/apt/keyrings/githubcli-archive-keyring.gpg
  register: gpg_key_check
  changed_when: false
  failed_when: false

- name: Download GH GPG key
  ansible.builtin.get_url:
    url: 'https://cli.github.com/packages/githubcli-archive-keyring.gpg'
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'
  when: gpg_key_check.rc != 0

- name: Add GH apt repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main'
    state: present

- name: Update apt and install gh cli
  ansible.builtin.apt:
    name: gh
    state: present
    update_cache: true
