---
- name: Check if terraform GPG key is already present
  ansible.builtin.command:
    cmd: gpg --list-keys --keyring /etc/apt/keyrings/hashicorp-archive-keyring.gpg
  register: gpg_key_check
  changed_when: false
  failed_when: false

- name: Download terraform GPG key
  ansible.builtin.get_url:
    url: 'https://apt.releases.hashicorp.com/gpg'
    dest: /tmp/hashicorp-archive-keyring.gpg
    mode: '0644'
  when: gpg_key_check.rc != 0

- name: Add terraform GPG key to apt keyring
  ansible.builtin.command:
    cmd: sudo gpg --dearmor -o /etc/apt/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp-archive-keyring.gpg
    creates: /etc/apt/keyrings/hashicorp-archive-keyring.gpg
  when: gpg_key_check.rc != 0

- name: Remove /tmp/hashicorp-archive-keyring.gpg
  ansible.builtin.file:
    path: /tmp/hashicorp-archive-keyring.gpg
    state: absent
  when: gpg_key_check.rc != 0

- name: Add terraform apt repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com noble main'
    state: present

- name: Update apt and install terraform cli
  ansible.builtin.apt:
    name: terraform
    state: present
    update_cache: true
