---
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Install common packages
  ansible.builtin.apt:
    name: '{{ item.name }}'
    state: present
  with_items: "{{ common_packages | default([]) }}"
